### ISSUE TITLE
Incorrect displaying of string layer

### ISSUE THREAD

**Issue by hermanguilliman** [sbrin/lopaka#1]
I have a problem with String layer. Used Windows 10 x64, Google Chrome 114, Opera 99.0, Edge 114. Anyway only Firefox 113 works fine 
![string](https://github.com/sbrin/lopaka/assets/32796452/9e21ff4c-7e67-43a6-a746-6686c1450f72)

**Comment by sbrin** [comment]
Thank you for reporting. Does it help to refresh the page? Do you see any related errors in browser dev tools? Is it helps to switch fonts back and forth?

**Comment by hermanguilliman** [comment]
> Thank you for reporting. Does it help to refresh the page? Do you see any related errors in browser dev tools? Does it help to switch fonts back and forth?

Only these
![image](https://github.com/sbrin/lopaka/assets/32796452/48273029-b47b-48f0-8f27-1667d1b8c442)

**Comment by jamisonderek** [comment]
For my computer, when I edit js/utils.js to have the maskBlack function use 
**imgData.data[i + 3] > 150** instead of **imgData.data[i + 3] === 255** then it works fine in both Windows 11 Edge and Windows 11 Chrome 115.0.5789.102.

If I increase the value to 170, then it still works in Edge but renders lines in Chrome for the haxr font.  At a value of 180 then I also get lines in Edge for haxr font.  At 200 then even the helvB font no longer renders correctly.

I'm not clear if using imgData.data[i + 3]>150 would pull in additional artifacts on working browsers, so maybe you have to do browser detection to determine the best value for the user?

**Comment by sbrin** [comment]
@jamisonderek thank you for pointing to masking function, I didn't expect it can ruin the text display.
I've pushed some updates including layers rendering logic. Please check it out.

**Comment by Racso** [comment]
Hi. I just got this issue.

Neither refreshing or switching fonts help.

![image](https://github.com/sbrin/lopaka/assets/26185386/33b60ace-06d1-47c8-addd-73f7ec361040)

**Comment by Racso** [comment]
I can confirm that @jamisonderek's change fixes the issue. I set `utils.js:125` to:

`imgData.data[i + 3] > 150`

and strings get correctly masked into the screen.

Running Chrome 115.0.5790.110 in Windows 10.

**Comment by sbrin** [comment]
@Racso thanks for sharing

I did some updates recently. Could you please check the latest code version?

**Comment by Racso** [comment]
It's way better! The tool is perfectly usable now. Thanks!

![image](https://github.com/sbrin/lopaka/assets/26185386/56dfccfd-2f20-4c93-8a5c-1f42e4c83a5a)

I'm not sure if it's intended or not, but there is some slight "shadowing" around the letters.

![image](https://github.com/sbrin/lopaka/assets/26185386/d5fd0300-ef09-4b8b-bddf-32504719ba74)
